version: '3'
services:
    db:
        image: 'postgres'
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=scruble
        volumes:
            - db-data:/var/lib/postgresql/data/
        ports:
            - '5432:5432'

volumes:
    db-data: